# Generated by Django 3.2.7 on 2021-09-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('image', models.ImageField(blank=True, height_field=100, upload_to='post_image', width_field=100)),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='publication date')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'posts',
            },
        ),
    ]
