# Generated by Django 3.2.7 on 2021-09-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='post_image', width_field=100),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
